apiVersion: apps/v1
kind: Deployment
metadata:
  name: delayedpayment-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delayedpaymentservice
  template:
    metadata:
      labels:
        app: delayedpaymentservice
    spec:
      containers:
        - name: delayedpaymentservice
          image: stilianstefanov/delayedpaymentservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: delayedpayment-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: delayedpaymentservice
  ports:
  - name: delayedpaymentservice
    protocol: TCP
    port: 8080
    targetPort: 8080