apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-mssql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-warehouse
  template:
    metadata:
      labels:
        app: mssql-warehouse
    spec:
      containers:
        - name: mssql-warehouse
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
          - name: MSSQL_PID
            value: "Express"
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: warehouse-mssql
                key: SA_PASSWORD
          volumeMounts:
          - mountPath: /var/opt/mssql/data
            name: mssqldb
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: warehouse-mssql-claim
---
apiVersion: v1
kind: Service
metadata:
  name: warehouse-mssql-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: mssql-warehouse
  ports:
  - name: mssql
    protocol: TCP
    port: 1433
    targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: warehouse-mssql-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: mssql-warehouse
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433